##将n个圆盘从q号柱转移到w号柱,其中q,w为{1,2,3}中的整数
##n为圆盘的个数
e<-0
f<-function(q,w,n){
  cat('将',n,'个圆盘从',q,'号柱转移到',w,'号柱结果如下：','\n')
  yiwei(q,w,n)
  cat('\n','总共需要移动',e,'次','\n')
  cat('提示：需再次运行脚本以刷新次数(因为次数变量为全局变量)')
}
yiwei<-function(q,w,n){
  if(n==1){
    e<<-e+1
    cat(q,'->',w,'\t')
    if(e%%6==0)cat('\n')
    }
  else{
    yiwei(q,6-q-w,n-1)
    yiwei(q,w,1)
    yiwei(6-q-w,w,n-1)
  }
}